//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "illustrator_wants")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i64,
    pub uid: i64,
    pub iid: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::Uid",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
    #[sea_orm(
        belongs_to = "super::illustrators::Entity",
        from = "Column::Iid",
        to = "super::illustrators::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Illustrators,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::illustrators::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Illustrators.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
