//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

pub mod prelude;

pub mod admins;
pub mod file_stores;
pub mod illustrator_acts;
pub mod illustrator_wants;
pub mod illustrators;
pub mod invites;
pub mod update_record;
pub mod users;
