//! SeaORM Entity. Generated by sea-orm-codegen 0.3.2

pub use super::illustrator_acts::Entity as IllustratorActs;
pub use super::illustrator_wants::Entity as IllustratorWants;
pub use super::illustrators::Entity as Illustrators;
pub use super::users::Entity as Users;
