-- Add migration script here
CREATE TABLE IF NOT EXISTS illustrators (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,

    name VARCHAR(32) NOT NULL UNIQUE,
    home VARCHAR(256) NOT NULL UNIQUE

)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS illustrator_wants(
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,

    uid BIGINT UNSIGNED NOT NULL,
    iid BIGINT UNSIGNED NOT NULL,

    FOREIGN KEY (uid) REFERENCES users(id),
    FOREIGN KEY (iid) REFERENCES illustrators(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;