-- Add migration script here
-- Your SQL goes here
CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT UNIQUE,

    name VARCHAR(32) NOT NULL UNIQUE,

    qq BIGINT UNSIGNED NOT NULL UNIQUE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;